apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  type: NodePort
  selector:
    app: transactions
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007
