name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant Execute Permission to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build the project
        run: ./mvnw clean package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/transactions:latest .
          docker push ghcr.io/${{ github.repository }}/transactions:latest

  deploy:
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v1.34.0

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mongo-service.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
